/*
 * Copyright (C) 2025 Darshan(@thisisthedarshan)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/* Version message print function */
export function version() {
  console.log(`
    ${package_name} ${ver} (Built on ${build_info} with NodeJS ${node_ver})
    ${copyright}
    
    Check the pss-langserver project on <https://github.com/thisisthedarshan/pss-langserver>
    `);
}
/* package name */
const package_name = 'pss-langserver';
/* Copyright */
const copyright = `
    Copyright (C) 2025 Darshan(@thisisthedarshan)
    
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.
`;
/* Version and build info - dynamically generated by npm script */
const ver = '0.2.0'
const build_info = 'March 06, 2025 at 11:43:24';
const node_ver = 'v22.14.0';